<Project Sdk="Microsoft.NET.Sdk">

  <!--Reference to the DataAccess project-->
  <ItemGroup>
    <ProjectReference Include="..\LogisticsPlanner.DataAccess\LogisticsPlanner.DataAccess.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
